// ignore_for_file: unused_import, unused_element
import 'package:flutter/foundation.dart';

// PushNotificationService - Firebase Cloud Messaging setup
//
// SETUP REQUIRED (manual steps):
// 1. Create Firebase project at console.firebase.google.com
// 2. Add Android app: package name from AndroidManifest.xml
// 3. Add iOS app: bundle ID from Xcode
// 4. Download google-services.json → android/app/
// 5. Download GoogleService-Info.plist → ios/Runner/
// 6. Run: flutter pub get
//
// This file provides the service skeleton - activate after Firebase setup.
// See FIREBASE_SETUP.md for the full step-by-step guide.

// After Firebase setup, uncomment these imports:
// import 'package:firebase_core/firebase_core.dart';
// import 'package:firebase_messaging/firebase_messaging.dart';
// import 'firebase_options.dart'; // generated by flutterfire configure

class PushNotificationService {
  static final instance = PushNotificationService._();
  PushNotificationService._();

  bool _initialized = false;

  Future<void> initialize() async {
    if (_initialized) return;

    // TODO: Uncomment after Firebase setup:
    // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
    // final messaging = FirebaseMessaging.instance;
    // await messaging.requestPermission(
    //   alert: true,
    //   badge: true,
    //   sound: true,
    // );
    // final token = await messaging.getToken();
    // debugPrint('[PushNotification] FCM token: $token');
    // await _saveTokenToSupabase(token);
    // FirebaseMessaging.onMessage.listen(_handleForegroundMessage);
    // FirebaseMessaging.onMessageOpenedApp.listen(_handleBackgroundTap);

    _initialized = true;
    debugPrint(
      '[PushNotification] Firebase setup required. '
      'See FIREBASE_SETUP.md for instructions.',
    );
  }

  Future<void> _saveTokenToSupabase(String? token) async {
    if (token == null) return;
    // TODO: Save FCM token to Supabase profiles table after auth is set up:
    // final userId = supabase.auth.currentUser?.id;
    // if (userId == null) return;
    // await supabase.from('profiles').update({'fcm_token': token}).eq('id', userId);
  }

  void _handleForegroundMessage(dynamic message) {
    // TODO: Show local notification using LocalNotificationService:
    // final notification = message.notification;
    // if (notification != null) {
    //   LocalNotificationService.showNotification(
    //     title: notification.title ?? '',
    //     body: notification.body ?? '',
    //   );
    // }
    debugPrint('[PushNotification] Foreground message: $message');
  }

  void _handleBackgroundTap(dynamic message) {
    // TODO: Navigate user to relevant screen based on message data
    debugPrint('[PushNotification] App opened from notification: $message');
  }
}
